### ISSUE TITLE
Crash on Android 5.1

### ISSUE THREAD

**Issue by dalb8** [happyalu/Flite-TTS-Engine-for-Android#44]
Crashes when tapping settings icon for Flite in Android Text-to-speech output Settings. Have observed this on OmniROM and with the following log on CM12.1. Built from source at 6d8a52ced0a42850d011f125fab2400425d1ff75

```
--------- beginning of system
I/ActivityManager(  487): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000 on display 0
V/WindowManager(  487): addAppToken: AppWindowToken{3f5e0f67 token=Token{38264726 ActivityRecord{5579a81 u0 com.android.settings/.SubSettings t372}}} to stack=1 task=372 at 3
D/SubSettings(32511): Launching fragment com.android.settings.tts.TtsEngineSettingsFragment
W/ContextImpl(32511): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1796 android.content.ContextWrapper.bindService:545 android.speech.tts.TextToSpeech.connectToEngine:800 android.speech.tts.TextToSpeech.initTts:751 android.speech.tts.TextToSpeech.<init>:723 
I/TextToSpeech(32511): Sucessfully bound to edu.cmu.cs.speech.tts.flite
I/ActivityManager(  487): START u0 {act=android.speech.tts.engine.CHECK_TTS_DATA pkg=edu.cmu.cs.speech.tts.flite cmp=edu.cmu.cs.speech.tts.flite/.CheckVoiceData} from uid 1000 on display 0
V/WindowManager(  487): addAppToken: AppWindowToken{18303a80 token=Token{13b23b03 ActivityRecord{d1fafb2 u0 edu.cmu.cs.speech.tts.flite/.CheckVoiceData t372}}} to stack=1 task=372 at 4
V/WindowManager(  487): Adding window Window{3d5ff744 u0 com.android.settings/com.android.settings.SubSettings} at 13 of 19 (after Window{345736e4 u0 com.android.settings/com.android.settings.SubSettings})
I/TextToSpeech(32511): Connected to ComponentInfo{edu.cmu.cs.speech.tts.flite/edu.cmu.cs.speech.tts.flite.FliteTtsService}
V/Flite_Java_FliteTtsService(32454): onIsLanguageAvailable
V/Flite_Java_FliteTtsService(32454): onIsLanguageAvailable
V/Flite_Java_FliteTtsService(32454): onIsLanguageAvailable
I/TextToSpeech(32511): Set up connection to ComponentInfo{edu.cmu.cs.speech.tts.flite/edu.cmu.cs.speech.tts.flite.FliteTtsService}
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-CAN-male_jmk
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/CAN/male_jmk.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-DEU-male_ahw
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/DEU/male_ahw.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-DEU-male_fem
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/DEU/male_fem.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-GBR-male_awb
I/Timeline(32511): Timeline: Activity_idle id: android.os.BinderProxy@36ce9c8a time:86923844
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-IND-female_axb
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/IND/female_axb.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-IND-male_aup
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/IND/male_aup.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-IND-male_gka
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/IND/male_gka.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-IND-male_ksp
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/IND/male_ksp.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-ISR-male_rxr
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/ISR/male_rxr.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-USA-female_clb
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/USA/female_clb.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-USA-female_slt
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-USA-male_bdl
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/USA/male_bdl.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: eng-USA-male_rms
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/eng/USA/male_rms.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: hin-IND-female_axb
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/hin/IND/female_axb.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: hin-IND-female_shraddha_rsvi
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/hin/IND/female_shraddha_rsvi.cg.flitevox
V/Flite_Java_Voice(32454): Checking for Voice Available: mar-IND-male_aup
E/Flite_Java_Voice(32454): Voice File not found: /storage/emulated/0/flite-data/cg/mar/IND/male_aup.cg.flitevox
W/TtsEngines(32511): Failed to convert eng-GBR-male_awb to a valid Locale object. Too many separators
W/TtsEngines(32511): Failed to convert eng-USA-female_slt to a valid Locale object. Too many separators
D/AndroidRuntime(32511): Shutting down VM
--------- beginning of crash
E/AndroidRuntime(32511): FATAL EXCEPTION: main
E/AndroidRuntime(32511): Process: com.android.settings, PID: 32511
E/AndroidRuntime(32511): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
E/AndroidRuntime(32511): 	at android.preference.ListPreference.findIndexOfValue(ListPreference.java:231)
E/AndroidRuntime(32511): 	at android.preference.ListPreference.getValueIndex(ListPreference.java:240)
E/AndroidRuntime(32511): 	at android.preference.ListPreference.getEntry(ListPreference.java:218)
E/AndroidRuntime(32511): 	at android.preference.ListPreference.getSummary(ListPreference.java:164)
E/AndroidRuntime(32511): 	at android.preference.Preference.onBindView(Preference.java:550)
E/AndroidRuntime(32511): 	at android.preference.Preference.getView(Preference.java:489)
E/AndroidRuntime(32511): 	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
E/AndroidRuntime(32511): 	at android.widget.AbsListView.obtainView(AbsListView.java:2349)
E/AndroidRuntime(32511): 	at android.widget.ListView.makeAndAddView(ListView.java:1864)
E/AndroidRuntime(32511): 	at android.widget.ListView.fillSpecific(ListView.java:1344)
E/AndroidRuntime(32511): 	at android.widget.ListView.layoutChildren(ListView.java:1651)
E/AndroidRuntime(32511): 	at android.widget.AbsListView.onLayout(AbsListView.java:2153)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(32511): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(32511): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(32511): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(32511): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(32511): 	at android.view.View.layout(View.java:15678)
E/AndroidRuntime(32511): 	at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(32511): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
E/AndroidRuntime(32511): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
E/AndroidRuntime(32511): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(32511): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
E/AndroidRuntime(32511): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(32511): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(32511): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(32511): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(32511): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(32511): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(32511): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(32511): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime(32511): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32511): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32511): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(32511): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/ActivityManager(  487):   Force finishing activity 1 com.android.settings/.SubSettings
W/ActivityManager(  487):   Force finishing activity 2 com.android.settings/.SubSettings
I/OpenGLRenderer(  487): Initialized EGL, version 1.4
W/ActivityManager(  487): Activity pause timeout for ActivityRecord{5579a81 u0 com.android.settings/.SubSettings t372 f}
I/Process (32511): Sending signal. PID: 32511 SIG: 9
I/WindowState(  487): WIN DEATH: Window{3d5ff744 u0 com.android.settings/com.android.settings.SubSettings}
I/WindowState(  487): WIN DEATH: Window{274c5e25 u0 com.android.settings/com.android.settings.SubSettings}
W/InputDispatcher(  487): channel '345736e4 com.android.settings/com.android.settings.SubSettings (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  487): channel '345736e4 com.android.settings/com.android.settings.SubSettings (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState(  487): WIN DEATH: W
```

**Comment by happyalu** [comment]
This seems to be happening because https://github.com/android/platform_frameworks_base/blob/master/core/java/android/speech/tts/TtsEngines.java#L72 added "_" as another locale separator, in addition to the "-" that it was using before.  I've switched the voices.list file to now use ";" as the separator within variants of languages, and that seems to have fixed the crash. Hence closing this issue. You will have to re-download voices.list from the settings to fix it.
